kind: pipeline
type: docker
name: default

steps:
- name: test
  image: alpine
  commands:
  - echo hello
  - echo world
  - pwd
  - ls
  - df

- name: build
  image: golang
  commands:
    - go build -o hello
    - ./hello
